name: Build FEYKIN AI EXE

on:
  push:
    tags:
      - 'v*' # Сборка будет запускаться, когда ты создаешь тег версии (напр. v1.0)

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install groq customtkinter pyinstaller

    - name: Build EXE with PyInstaller
      run: |
        # Мы используем ту самую команду с пробросом путей customtkinter
        python -m PyInstaller --noconfirm --onefile --windowed --add-data "$(python -c 'import customtkinter; print(customtkinter.__path__[0])');customtkinter/" feykin_ai_pro.py

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/feykin_ai_pro.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
